version: '3.9'

services:

  app:
    build:
      context: node

    networks:
      - node-network

    volumes:
      - ./node:/usr/src/app
    tty: true
    container_name: app
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root

    networks:
      - node-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    image: sergiommjunior/nginx:prod
    container_name: nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
